/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1beta1

import (
	"github.com/kcp-dev/logicalcluster/v3"
)

// CSIDriverListerExpansion allows custom methods to be added to
// CSIDriverLister.
type CSIDriverListerExpansion interface{}

// CSIDriverClusterListerExpansion allows custom methods to be added to
// CSIDriverLister.
type CSIDriverClusterListerExpansion interface {
	// Cluster returns a lister that can list and get CSIDriver in one workspace.
	Cluster(clusterName logicalcluster.Name) CSIDriverLister
}

// CSINodeListerExpansion allows custom methods to be added to
// CSINodeLister.
type CSINodeListerExpansion interface{}

// CSINodeClusterListerExpansion allows custom methods to be added to
// CSINodeLister.
type CSINodeClusterListerExpansion interface {
	// Cluster returns a lister that can list and get CSINode in one workspace.
	Cluster(clusterName logicalcluster.Name) CSINodeLister
}

// CSIStorageCapacityListerExpansion allows custom methods to be added to
// CSIStorageCapacityLister.
type CSIStorageCapacityListerExpansion interface{}

// CSIStorageCapacityClusterListerExpansion allows custom methods to be added to
// CSIStorageCapacityLister.
type CSIStorageCapacityClusterListerExpansion interface {
	// Cluster returns a lister that can list and get CSIStorageCapacity in one workspace.
	Cluster(clusterName logicalcluster.Name) CSIStorageCapacityLister
}

// CSIStorageCapacityNamespaceListerExpansion allows custom methods to be added to
// CSIStorageCapacityNamespaceLister.
type CSIStorageCapacityNamespaceListerExpansion interface{}

// StorageClassListerExpansion allows custom methods to be added to
// StorageClassLister.
type StorageClassListerExpansion interface{}

// StorageClassClusterListerExpansion allows custom methods to be added to
// StorageClassLister.
type StorageClassClusterListerExpansion interface {
	// Cluster returns a lister that can list and get StorageClass in one workspace.
	Cluster(clusterName logicalcluster.Name) StorageClassLister
}

// VolumeAttachmentListerExpansion allows custom methods to be added to
// VolumeAttachmentLister.
type VolumeAttachmentListerExpansion interface{}

// VolumeAttachmentClusterListerExpansion allows custom methods to be added to
// VolumeAttachmentLister.
type VolumeAttachmentClusterListerExpansion interface {
	// Cluster returns a lister that can list and get VolumeAttachment in one workspace.
	Cluster(clusterName logicalcluster.Name) VolumeAttachmentLister
}

// VolumeAttributesClassListerExpansion allows custom methods to be added to
// VolumeAttributesClassLister.
type VolumeAttributesClassListerExpansion interface{}

// VolumeAttributesClassClusterListerExpansion allows custom methods to be added to
// VolumeAttributesClassLister.
type VolumeAttributesClassClusterListerExpansion interface {
	// Cluster returns a lister that can list and get VolumeAttributesClass in one workspace.
	Cluster(clusterName logicalcluster.Name) VolumeAttributesClassLister
}
