/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1beta1

import (
	"context"

	"github.com/kcp-dev/logicalcluster/v3"
	v1beta1 "k8s.io/api/batch/v1beta1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
	batchv1beta1client "k8s.io/client-go/kuberentes/typed/batch/v1beta1"
	batchv1beta1 "k8s.io/code-generator/examples/upstream/applyconfiguration/batch/v1beta1"
	scheme "k8s.io/code-generator/examples/upstream/clientset/versioned/scheme"
)

// CronJobsClusterGetter has a method to return a CronJobClusterInterface.
// A group's client should implement this interface.
type CronJobsClusterGetter interface {
	CronJobs(namespace string) CronJobClusterInterface
}

// CronJobInterface has methods to work with CronJob resources.
type CronJobClusterInterface interface {
	Cluster(logicalcluster.Path) batchv1beta1client.CronJobInterface

	List(ctx context.Context, opts v1.ListOptions) (*v1beta1.CronJobList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	CronJobExpansion
}

// cronJobs implements CronJobInterface
type cronJobs struct {
	*gentype.ClientWithListAndApply[*v1beta1.CronJob, *v1beta1.CronJobList, *batchv1beta1.CronJobApplyConfiguration]
}

// newCronJobs returns a CronJobs
func newCronJobs(c *BatchV1beta1Client, namespace string) *cronJobs {
	return &cronJobs{
		gentype.NewClientWithListAndApply[*v1beta1.CronJob, *v1beta1.CronJobList, *batchv1beta1.CronJobApplyConfiguration](
			"cronjobs",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *v1beta1.CronJob { return &v1beta1.CronJob{} },
			func() *v1beta1.CronJobList { return &v1beta1.CronJobList{} }),
	}
}
