/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"context"

	"github.com/kcp-dev/logicalcluster/v3"
	storagev1 "k8s.io/api/storage/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
	storagev1client "k8s.io/client-go/kuberentes/typed/storage/v1"
	applyconfigurationstoragev1 "k8s.io/code-generator/examples/upstream/applyconfiguration/storage/v1"
	scheme "k8s.io/code-generator/examples/upstream/clientset/versioned/scheme"
)

// CSIDriversClusterGetter has a method to return a CSIDriverClusterInterface.
// A group's client should implement this interface.
type CSIDriversClusterGetter interface {
	CSIDrivers() CSIDriverClusterInterface
}

// CSIDriverInterface has methods to work with CSIDriver resources.
type CSIDriverClusterInterface interface {
	Cluster(logicalcluster.Path) storagev1client.CSIDriverInterface

	List(ctx context.Context, opts v1.ListOptions) (*storagev1.CSIDriverList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	CSIDriverExpansion
}

// cSIDrivers implements CSIDriverInterface
type cSIDrivers struct {
	*gentype.ClientWithListAndApply[*storagev1.CSIDriver, *storagev1.CSIDriverList, *applyconfigurationstoragev1.CSIDriverApplyConfiguration]
}

// newCSIDrivers returns a CSIDrivers
func newCSIDrivers(c *StorageV1Client) *cSIDrivers {
	return &cSIDrivers{
		gentype.NewClientWithListAndApply[*storagev1.CSIDriver, *storagev1.CSIDriverList, *applyconfigurationstoragev1.CSIDriverApplyConfiguration](
			"csidrivers",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *storagev1.CSIDriver { return &storagev1.CSIDriver{} },
			func() *storagev1.CSIDriverList { return &storagev1.CSIDriverList{} }),
	}
}
