/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"context"

	"github.com/kcp-dev/logicalcluster/v3"
	storagev1 "k8s.io/api/storage/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
	storagev1client "k8s.io/client-go/kuberentes/typed/storage/v1"
	applyconfigurationstoragev1 "k8s.io/code-generator/examples/upstream/applyconfiguration/storage/v1"
	scheme "k8s.io/code-generator/examples/upstream/clientset/versioned/scheme"
)

// StorageClassesClusterGetter has a method to return a StorageClassClusterInterface.
// A group's client should implement this interface.
type StorageClassesClusterGetter interface {
	StorageClasses() StorageClassClusterInterface
}

// StorageClassInterface has methods to work with StorageClass resources.
type StorageClassClusterInterface interface {
	Cluster(logicalcluster.Path) storagev1client.StorageClassInterface

	List(ctx context.Context, opts v1.ListOptions) (*storagev1.StorageClassList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	StorageClassExpansion
}

// storageClasses implements StorageClassInterface
type storageClasses struct {
	*gentype.ClientWithListAndApply[*storagev1.StorageClass, *storagev1.StorageClassList, *applyconfigurationstoragev1.StorageClassApplyConfiguration]
}

// newStorageClasses returns a StorageClasses
func newStorageClasses(c *StorageV1Client) *storageClasses {
	return &storageClasses{
		gentype.NewClientWithListAndApply[*storagev1.StorageClass, *storagev1.StorageClassList, *applyconfigurationstoragev1.StorageClassApplyConfiguration](
			"storageclasses",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *storagev1.StorageClass { return &storagev1.StorageClass{} },
			func() *storagev1.StorageClassList { return &storagev1.StorageClassList{} }),
	}
}
