/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"

	"github.com/kcp-dev/logicalcluster/v3"
	v1alpha1 "k8s.io/api/networking/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
	networkingv1alpha1client "k8s.io/client-go/kuberentes/typed/networking/v1alpha1"
	networkingv1alpha1 "k8s.io/code-generator/examples/upstream/applyconfiguration/networking/v1alpha1"
	scheme "k8s.io/code-generator/examples/upstream/clientset/versioned/scheme"
)

// IPAddressesClusterGetter has a method to return a IPAddressClusterInterface.
// A group's client should implement this interface.
type IPAddressesClusterGetter interface {
	IPAddresses() IPAddressClusterInterface
}

// IPAddressInterface has methods to work with IPAddress resources.
type IPAddressClusterInterface interface {
	Cluster(logicalcluster.Path) networkingv1alpha1client.IPAddressInterface

	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.IPAddressList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	IPAddressExpansion
}

// iPAddresses implements IPAddressInterface
type iPAddresses struct {
	*gentype.ClientWithListAndApply[*v1alpha1.IPAddress, *v1alpha1.IPAddressList, *networkingv1alpha1.IPAddressApplyConfiguration]
}

// newIPAddresses returns a IPAddresses
func newIPAddresses(c *NetworkingV1alpha1Client) *iPAddresses {
	return &iPAddresses{
		gentype.NewClientWithListAndApply[*v1alpha1.IPAddress, *v1alpha1.IPAddressList, *networkingv1alpha1.IPAddressApplyConfiguration](
			"ipaddresses",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *v1alpha1.IPAddress { return &v1alpha1.IPAddress{} },
			func() *v1alpha1.IPAddressList { return &v1alpha1.IPAddressList{} }),
	}
}
