/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"context"

	"github.com/kcp-dev/logicalcluster/v3"
	corev1 "k8s.io/api/core/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
	corev1client "k8s.io/client-go/kuberentes/typed/core/v1"
	applyconfigurationcorev1 "k8s.io/code-generator/examples/upstream/applyconfiguration/core/v1"
	scheme "k8s.io/code-generator/examples/upstream/clientset/versioned/scheme"
)

// ComponentStatusesClusterGetter has a method to return a ComponentStatusClusterInterface.
// A group's client should implement this interface.
type ComponentStatusesClusterGetter interface {
	ComponentStatuses() ComponentStatusClusterInterface
}

// ComponentStatusInterface has methods to work with ComponentStatus resources.
type ComponentStatusClusterInterface interface {
	Cluster(logicalcluster.Path) corev1client.ComponentStatusInterface

	List(ctx context.Context, opts v1.ListOptions) (*corev1.ComponentStatusList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	ComponentStatusExpansion
}

// componentStatuses implements ComponentStatusInterface
type componentStatuses struct {
	*gentype.ClientWithListAndApply[*corev1.ComponentStatus, *corev1.ComponentStatusList, *applyconfigurationcorev1.ComponentStatusApplyConfiguration]
}

// newComponentStatuses returns a ComponentStatuses
func newComponentStatuses(c *CoreV1Client) *componentStatuses {
	return &componentStatuses{
		gentype.NewClientWithListAndApply[*corev1.ComponentStatus, *corev1.ComponentStatusList, *applyconfigurationcorev1.ComponentStatusApplyConfiguration](
			"componentstatuses",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *corev1.ComponentStatus { return &corev1.ComponentStatus{} },
			func() *corev1.ComponentStatusList { return &corev1.ComponentStatusList{} }),
	}
}
