/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"context"

	"github.com/kcp-dev/logicalcluster/v3"
	corev1 "k8s.io/api/core/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
	corev1client "k8s.io/client-go/kuberentes/typed/core/v1"
	applyconfigurationcorev1 "k8s.io/code-generator/examples/upstream/applyconfiguration/core/v1"
	scheme "k8s.io/code-generator/examples/upstream/clientset/versioned/scheme"
)

// EndpointsesClusterGetter has a method to return a EndpointsClusterInterface.
// A group's client should implement this interface.
type EndpointsesClusterGetter interface {
	Endpointses(namespace string) EndpointsClusterInterface
}

// EndpointsInterface has methods to work with Endpoints resources.
type EndpointsClusterInterface interface {
	Cluster(logicalcluster.Path) corev1client.EndpointsInterface

	List(ctx context.Context, opts v1.ListOptions) (*corev1.EndpointsList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	EndpointsExpansion
}

// endpointses implements EndpointsInterface
type endpointses struct {
	*gentype.ClientWithListAndApply[*corev1.Endpoints, *corev1.EndpointsList, *applyconfigurationcorev1.EndpointsApplyConfiguration]
}

// newEndpointses returns a Endpointses
func newEndpointses(c *CoreV1Client, namespace string) *endpointses {
	return &endpointses{
		gentype.NewClientWithListAndApply[*corev1.Endpoints, *corev1.EndpointsList, *applyconfigurationcorev1.EndpointsApplyConfiguration](
			"endpointses",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *corev1.Endpoints { return &corev1.Endpoints{} },
			func() *corev1.EndpointsList { return &corev1.EndpointsList{} }),
	}
}
