/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"context"

	"github.com/kcp-dev/logicalcluster/v3"
	corev1 "k8s.io/api/core/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
	corev1client "k8s.io/client-go/kuberentes/typed/core/v1"
	applyconfigurationcorev1 "k8s.io/code-generator/examples/upstream/applyconfiguration/core/v1"
	scheme "k8s.io/code-generator/examples/upstream/clientset/versioned/scheme"
)

// EventsClusterGetter has a method to return a EventClusterInterface.
// A group's client should implement this interface.
type EventsClusterGetter interface {
	Events(namespace string) EventClusterInterface
}

// EventInterface has methods to work with Event resources.
type EventClusterInterface interface {
	Cluster(logicalcluster.Path) corev1client.EventInterface

	List(ctx context.Context, opts v1.ListOptions) (*corev1.EventList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	EventExpansion
}

// events implements EventInterface
type events struct {
	*gentype.ClientWithListAndApply[*corev1.Event, *corev1.EventList, *applyconfigurationcorev1.EventApplyConfiguration]
}

// newEvents returns a Events
func newEvents(c *CoreV1Client, namespace string) *events {
	return &events{
		gentype.NewClientWithListAndApply[*corev1.Event, *corev1.EventList, *applyconfigurationcorev1.EventApplyConfiguration](
			"events",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *corev1.Event { return &corev1.Event{} },
			func() *corev1.EventList { return &corev1.EventList{} }),
	}
}
