/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"context"

	"github.com/kcp-dev/logicalcluster/v3"
	corev1 "k8s.io/api/core/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
	corev1client "k8s.io/client-go/kuberentes/typed/core/v1"
	applyconfigurationcorev1 "k8s.io/code-generator/examples/upstream/applyconfiguration/core/v1"
	scheme "k8s.io/code-generator/examples/upstream/clientset/versioned/scheme"
)

// NodesClusterGetter has a method to return a NodeClusterInterface.
// A group's client should implement this interface.
type NodesClusterGetter interface {
	Nodes() NodeClusterInterface
}

// NodeInterface has methods to work with Node resources.
type NodeClusterInterface interface {
	Cluster(logicalcluster.Path) corev1client.NodeInterface

	List(ctx context.Context, opts v1.ListOptions) (*corev1.NodeList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	NodeExpansion
}

// nodes implements NodeInterface
type nodes struct {
	*gentype.ClientWithListAndApply[*corev1.Node, *corev1.NodeList, *applyconfigurationcorev1.NodeApplyConfiguration]
}

// newNodes returns a Nodes
func newNodes(c *CoreV1Client) *nodes {
	return &nodes{
		gentype.NewClientWithListAndApply[*corev1.Node, *corev1.NodeList, *applyconfigurationcorev1.NodeApplyConfiguration](
			"nodes",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *corev1.Node { return &corev1.Node{} },
			func() *corev1.NodeList { return &corev1.NodeList{} }),
	}
}
