/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"context"

	"github.com/kcp-dev/logicalcluster/v3"
	corev1 "k8s.io/api/core/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
	corev1client "k8s.io/client-go/kuberentes/typed/core/v1"
	applyconfigurationcorev1 "k8s.io/code-generator/examples/upstream/applyconfiguration/core/v1"
	scheme "k8s.io/code-generator/examples/upstream/clientset/versioned/scheme"
)

// PersistentVolumesClusterGetter has a method to return a PersistentVolumeClusterInterface.
// A group's client should implement this interface.
type PersistentVolumesClusterGetter interface {
	PersistentVolumes() PersistentVolumeClusterInterface
}

// PersistentVolumeInterface has methods to work with PersistentVolume resources.
type PersistentVolumeClusterInterface interface {
	Cluster(logicalcluster.Path) corev1client.PersistentVolumeInterface

	List(ctx context.Context, opts v1.ListOptions) (*corev1.PersistentVolumeList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	PersistentVolumeExpansion
}

// persistentVolumes implements PersistentVolumeInterface
type persistentVolumes struct {
	*gentype.ClientWithListAndApply[*corev1.PersistentVolume, *corev1.PersistentVolumeList, *applyconfigurationcorev1.PersistentVolumeApplyConfiguration]
}

// newPersistentVolumes returns a PersistentVolumes
func newPersistentVolumes(c *CoreV1Client) *persistentVolumes {
	return &persistentVolumes{
		gentype.NewClientWithListAndApply[*corev1.PersistentVolume, *corev1.PersistentVolumeList, *applyconfigurationcorev1.PersistentVolumeApplyConfiguration](
			"persistentvolumes",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *corev1.PersistentVolume { return &corev1.PersistentVolume{} },
			func() *corev1.PersistentVolumeList { return &corev1.PersistentVolumeList{} }),
	}
}
