/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha3

import (
	"context"

	"github.com/kcp-dev/logicalcluster/v3"
	v1alpha3 "k8s.io/api/resource/v1alpha3"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
	resourcev1alpha3client "k8s.io/client-go/kuberentes/typed/resource/v1alpha3"
	resourcev1alpha3 "k8s.io/code-generator/examples/upstream/applyconfiguration/resource/v1alpha3"
	scheme "k8s.io/code-generator/examples/upstream/clientset/versioned/scheme"
)

// DeviceClassesClusterGetter has a method to return a DeviceClassClusterInterface.
// A group's client should implement this interface.
type DeviceClassesClusterGetter interface {
	DeviceClasses() DeviceClassClusterInterface
}

// DeviceClassInterface has methods to work with DeviceClass resources.
type DeviceClassClusterInterface interface {
	Cluster(logicalcluster.Path) resourcev1alpha3client.DeviceClassInterface

	List(ctx context.Context, opts v1.ListOptions) (*v1alpha3.DeviceClassList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	DeviceClassExpansion
}

// deviceClasses implements DeviceClassInterface
type deviceClasses struct {
	*gentype.ClientWithListAndApply[*v1alpha3.DeviceClass, *v1alpha3.DeviceClassList, *resourcev1alpha3.DeviceClassApplyConfiguration]
}

// newDeviceClasses returns a DeviceClasses
func newDeviceClasses(c *ResourceV1alpha3Client) *deviceClasses {
	return &deviceClasses{
		gentype.NewClientWithListAndApply[*v1alpha3.DeviceClass, *v1alpha3.DeviceClassList, *resourcev1alpha3.DeviceClassApplyConfiguration](
			"deviceclasses",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *v1alpha3.DeviceClass { return &v1alpha3.DeviceClass{} },
			func() *v1alpha3.DeviceClassList { return &v1alpha3.DeviceClassList{} }),
	}
}
