/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha3

import (
	"context"

	"github.com/kcp-dev/logicalcluster/v3"
	v1alpha3 "k8s.io/api/resource/v1alpha3"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
	resourcev1alpha3client "k8s.io/client-go/kuberentes/typed/resource/v1alpha3"
	resourcev1alpha3 "k8s.io/code-generator/examples/upstream/applyconfiguration/resource/v1alpha3"
	scheme "k8s.io/code-generator/examples/upstream/clientset/versioned/scheme"
)

// PodSchedulingContextsClusterGetter has a method to return a PodSchedulingContextClusterInterface.
// A group's client should implement this interface.
type PodSchedulingContextsClusterGetter interface {
	PodSchedulingContexts(namespace string) PodSchedulingContextClusterInterface
}

// PodSchedulingContextInterface has methods to work with PodSchedulingContext resources.
type PodSchedulingContextClusterInterface interface {
	Cluster(logicalcluster.Path) resourcev1alpha3client.PodSchedulingContextInterface

	List(ctx context.Context, opts v1.ListOptions) (*v1alpha3.PodSchedulingContextList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	PodSchedulingContextExpansion
}

// podSchedulingContexts implements PodSchedulingContextInterface
type podSchedulingContexts struct {
	*gentype.ClientWithListAndApply[*v1alpha3.PodSchedulingContext, *v1alpha3.PodSchedulingContextList, *resourcev1alpha3.PodSchedulingContextApplyConfiguration]
}

// newPodSchedulingContexts returns a PodSchedulingContexts
func newPodSchedulingContexts(c *ResourceV1alpha3Client, namespace string) *podSchedulingContexts {
	return &podSchedulingContexts{
		gentype.NewClientWithListAndApply[*v1alpha3.PodSchedulingContext, *v1alpha3.PodSchedulingContextList, *resourcev1alpha3.PodSchedulingContextApplyConfiguration](
			"podschedulingcontexts",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *v1alpha3.PodSchedulingContext { return &v1alpha3.PodSchedulingContext{} },
			func() *v1alpha3.PodSchedulingContextList { return &v1alpha3.PodSchedulingContextList{} }),
	}
}
