/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1beta1

import (
	"context"

	"github.com/kcp-dev/logicalcluster/v3"
	v1beta1 "k8s.io/api/scheduling/v1beta1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
	schedulingv1beta1client "k8s.io/client-go/kuberentes/typed/scheduling/v1beta1"
	schedulingv1beta1 "k8s.io/code-generator/examples/upstream/applyconfiguration/scheduling/v1beta1"
	scheme "k8s.io/code-generator/examples/upstream/clientset/versioned/scheme"
)

// PriorityClassesClusterGetter has a method to return a PriorityClassClusterInterface.
// A group's client should implement this interface.
type PriorityClassesClusterGetter interface {
	PriorityClasses() PriorityClassClusterInterface
}

// PriorityClassInterface has methods to work with PriorityClass resources.
type PriorityClassClusterInterface interface {
	Cluster(logicalcluster.Path) schedulingv1beta1client.PriorityClassInterface

	List(ctx context.Context, opts v1.ListOptions) (*v1beta1.PriorityClassList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	PriorityClassExpansion
}

// priorityClasses implements PriorityClassInterface
type priorityClasses struct {
	*gentype.ClientWithListAndApply[*v1beta1.PriorityClass, *v1beta1.PriorityClassList, *schedulingv1beta1.PriorityClassApplyConfiguration]
}

// newPriorityClasses returns a PriorityClasses
func newPriorityClasses(c *SchedulingV1beta1Client) *priorityClasses {
	return &priorityClasses{
		gentype.NewClientWithListAndApply[*v1beta1.PriorityClass, *v1beta1.PriorityClassList, *schedulingv1beta1.PriorityClassApplyConfiguration](
			"priorityclasses",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *v1beta1.PriorityClass { return &v1beta1.PriorityClass{} },
			func() *v1beta1.PriorityClassList { return &v1beta1.PriorityClassList{} }),
	}
}
