/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"context"

	"github.com/kcp-dev/logicalcluster/v3"
	policyv1 "k8s.io/api/policy/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
	policyv1client "k8s.io/client-go/kuberentes/typed/policy/v1"
	applyconfigurationpolicyv1 "k8s.io/code-generator/examples/upstream/applyconfiguration/policy/v1"
	scheme "k8s.io/code-generator/examples/upstream/clientset/versioned/scheme"
)

// PodDisruptionBudgetsClusterGetter has a method to return a PodDisruptionBudgetClusterInterface.
// A group's client should implement this interface.
type PodDisruptionBudgetsClusterGetter interface {
	PodDisruptionBudgets(namespace string) PodDisruptionBudgetClusterInterface
}

// PodDisruptionBudgetInterface has methods to work with PodDisruptionBudget resources.
type PodDisruptionBudgetClusterInterface interface {
	Cluster(logicalcluster.Path) policyv1client.PodDisruptionBudgetInterface

	List(ctx context.Context, opts v1.ListOptions) (*policyv1.PodDisruptionBudgetList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	PodDisruptionBudgetExpansion
}

// podDisruptionBudgets implements PodDisruptionBudgetInterface
type podDisruptionBudgets struct {
	*gentype.ClientWithListAndApply[*policyv1.PodDisruptionBudget, *policyv1.PodDisruptionBudgetList, *applyconfigurationpolicyv1.PodDisruptionBudgetApplyConfiguration]
}

// newPodDisruptionBudgets returns a PodDisruptionBudgets
func newPodDisruptionBudgets(c *PolicyV1Client, namespace string) *podDisruptionBudgets {
	return &podDisruptionBudgets{
		gentype.NewClientWithListAndApply[*policyv1.PodDisruptionBudget, *policyv1.PodDisruptionBudgetList, *applyconfigurationpolicyv1.PodDisruptionBudgetApplyConfiguration](
			"poddisruptionbudgets",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *policyv1.PodDisruptionBudget { return &policyv1.PodDisruptionBudget{} },
			func() *policyv1.PodDisruptionBudgetList { return &policyv1.PodDisruptionBudgetList{} }),
	}
}
