/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	"github.com/kcp-dev/logicalcluster/v3"
)

// ComponentStatusListerExpansion allows custom methods to be added to
// ComponentStatusLister.
type ComponentStatusListerExpansion interface{}

// ComponentStatusClusterListerExpansion allows custom methods to be added to
// ComponentStatusLister.
type ComponentStatusClusterListerExpansion interface {
	// Cluster returns a lister that can list and get ComponentStatus in one workspace.
	Cluster(clusterName logicalcluster.Name) ComponentStatusLister
}

// ConfigMapListerExpansion allows custom methods to be added to
// ConfigMapLister.
type ConfigMapListerExpansion interface{}

// ConfigMapClusterListerExpansion allows custom methods to be added to
// ConfigMapLister.
type ConfigMapClusterListerExpansion interface {
	// Cluster returns a lister that can list and get ConfigMap in one workspace.
	Cluster(clusterName logicalcluster.Name) ConfigMapLister
}

// ConfigMapNamespaceListerExpansion allows custom methods to be added to
// ConfigMapNamespaceLister.
type ConfigMapNamespaceListerExpansion interface{}

// EndpointsListerExpansion allows custom methods to be added to
// EndpointsLister.
type EndpointsListerExpansion interface{}

// EndpointsClusterListerExpansion allows custom methods to be added to
// EndpointsLister.
type EndpointsClusterListerExpansion interface {
	// Cluster returns a lister that can list and get Endpoints in one workspace.
	Cluster(clusterName logicalcluster.Name) EndpointsLister
}

// EndpointsNamespaceListerExpansion allows custom methods to be added to
// EndpointsNamespaceLister.
type EndpointsNamespaceListerExpansion interface{}

// EventListerExpansion allows custom methods to be added to
// EventLister.
type EventListerExpansion interface{}

// EventClusterListerExpansion allows custom methods to be added to
// EventLister.
type EventClusterListerExpansion interface {
	// Cluster returns a lister that can list and get Event in one workspace.
	Cluster(clusterName logicalcluster.Name) EventLister
}

// EventNamespaceListerExpansion allows custom methods to be added to
// EventNamespaceLister.
type EventNamespaceListerExpansion interface{}

// LimitRangeListerExpansion allows custom methods to be added to
// LimitRangeLister.
type LimitRangeListerExpansion interface{}

// LimitRangeClusterListerExpansion allows custom methods to be added to
// LimitRangeLister.
type LimitRangeClusterListerExpansion interface {
	// Cluster returns a lister that can list and get LimitRange in one workspace.
	Cluster(clusterName logicalcluster.Name) LimitRangeLister
}

// LimitRangeNamespaceListerExpansion allows custom methods to be added to
// LimitRangeNamespaceLister.
type LimitRangeNamespaceListerExpansion interface{}

// NamespaceListerExpansion allows custom methods to be added to
// NamespaceLister.
type NamespaceListerExpansion interface{}

// NamespaceClusterListerExpansion allows custom methods to be added to
// NamespaceLister.
type NamespaceClusterListerExpansion interface {
	// Cluster returns a lister that can list and get Namespace in one workspace.
	Cluster(clusterName logicalcluster.Name) NamespaceLister
}

// NodeListerExpansion allows custom methods to be added to
// NodeLister.
type NodeListerExpansion interface{}

// NodeClusterListerExpansion allows custom methods to be added to
// NodeLister.
type NodeClusterListerExpansion interface {
	// Cluster returns a lister that can list and get Node in one workspace.
	Cluster(clusterName logicalcluster.Name) NodeLister
}

// PersistentVolumeListerExpansion allows custom methods to be added to
// PersistentVolumeLister.
type PersistentVolumeListerExpansion interface{}

// PersistentVolumeClusterListerExpansion allows custom methods to be added to
// PersistentVolumeLister.
type PersistentVolumeClusterListerExpansion interface {
	// Cluster returns a lister that can list and get PersistentVolume in one workspace.
	Cluster(clusterName logicalcluster.Name) PersistentVolumeLister
}

// PersistentVolumeClaimListerExpansion allows custom methods to be added to
// PersistentVolumeClaimLister.
type PersistentVolumeClaimListerExpansion interface{}

// PersistentVolumeClaimClusterListerExpansion allows custom methods to be added to
// PersistentVolumeClaimLister.
type PersistentVolumeClaimClusterListerExpansion interface {
	// Cluster returns a lister that can list and get PersistentVolumeClaim in one workspace.
	Cluster(clusterName logicalcluster.Name) PersistentVolumeClaimLister
}

// PersistentVolumeClaimNamespaceListerExpansion allows custom methods to be added to
// PersistentVolumeClaimNamespaceLister.
type PersistentVolumeClaimNamespaceListerExpansion interface{}

// PodListerExpansion allows custom methods to be added to
// PodLister.
type PodListerExpansion interface{}

// PodClusterListerExpansion allows custom methods to be added to
// PodLister.
type PodClusterListerExpansion interface {
	// Cluster returns a lister that can list and get Pod in one workspace.
	Cluster(clusterName logicalcluster.Name) PodLister
}

// PodNamespaceListerExpansion allows custom methods to be added to
// PodNamespaceLister.
type PodNamespaceListerExpansion interface{}

// PodTemplateListerExpansion allows custom methods to be added to
// PodTemplateLister.
type PodTemplateListerExpansion interface{}

// PodTemplateClusterListerExpansion allows custom methods to be added to
// PodTemplateLister.
type PodTemplateClusterListerExpansion interface {
	// Cluster returns a lister that can list and get PodTemplate in one workspace.
	Cluster(clusterName logicalcluster.Name) PodTemplateLister
}

// PodTemplateNamespaceListerExpansion allows custom methods to be added to
// PodTemplateNamespaceLister.
type PodTemplateNamespaceListerExpansion interface{}

// ReplicationControllerListerExpansion allows custom methods to be added to
// ReplicationControllerLister.
type ReplicationControllerListerExpansion interface{}

// ReplicationControllerClusterListerExpansion allows custom methods to be added to
// ReplicationControllerLister.
type ReplicationControllerClusterListerExpansion interface {
	// Cluster returns a lister that can list and get ReplicationController in one workspace.
	Cluster(clusterName logicalcluster.Name) ReplicationControllerLister
}

// ReplicationControllerNamespaceListerExpansion allows custom methods to be added to
// ReplicationControllerNamespaceLister.
type ReplicationControllerNamespaceListerExpansion interface{}

// ResourceQuotaListerExpansion allows custom methods to be added to
// ResourceQuotaLister.
type ResourceQuotaListerExpansion interface{}

// ResourceQuotaClusterListerExpansion allows custom methods to be added to
// ResourceQuotaLister.
type ResourceQuotaClusterListerExpansion interface {
	// Cluster returns a lister that can list and get ResourceQuota in one workspace.
	Cluster(clusterName logicalcluster.Name) ResourceQuotaLister
}

// ResourceQuotaNamespaceListerExpansion allows custom methods to be added to
// ResourceQuotaNamespaceLister.
type ResourceQuotaNamespaceListerExpansion interface{}

// SecretListerExpansion allows custom methods to be added to
// SecretLister.
type SecretListerExpansion interface{}

// SecretClusterListerExpansion allows custom methods to be added to
// SecretLister.
type SecretClusterListerExpansion interface {
	// Cluster returns a lister that can list and get Secret in one workspace.
	Cluster(clusterName logicalcluster.Name) SecretLister
}

// SecretNamespaceListerExpansion allows custom methods to be added to
// SecretNamespaceLister.
type SecretNamespaceListerExpansion interface{}

// ServiceListerExpansion allows custom methods to be added to
// ServiceLister.
type ServiceListerExpansion interface{}

// ServiceClusterListerExpansion allows custom methods to be added to
// ServiceLister.
type ServiceClusterListerExpansion interface {
	// Cluster returns a lister that can list and get Service in one workspace.
	Cluster(clusterName logicalcluster.Name) ServiceLister
}

// ServiceNamespaceListerExpansion allows custom methods to be added to
// ServiceNamespaceLister.
type ServiceNamespaceListerExpansion interface{}

// ServiceAccountListerExpansion allows custom methods to be added to
// ServiceAccountLister.
type ServiceAccountListerExpansion interface{}

// ServiceAccountClusterListerExpansion allows custom methods to be added to
// ServiceAccountLister.
type ServiceAccountClusterListerExpansion interface {
	// Cluster returns a lister that can list and get ServiceAccount in one workspace.
	Cluster(clusterName logicalcluster.Name) ServiceAccountLister
}

// ServiceAccountNamespaceListerExpansion allows custom methods to be added to
// ServiceAccountNamespaceLister.
type ServiceAccountNamespaceListerExpansion interface{}
