/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"context"

	"github.com/kcp-dev/logicalcluster/v3"
	nodev1 "k8s.io/api/node/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
	nodev1client "k8s.io/client-go/kuberentes/typed/node/v1"
	applyconfigurationnodev1 "k8s.io/code-generator/examples/upstream/applyconfiguration/node/v1"
	scheme "k8s.io/code-generator/examples/upstream/clientset/versioned/scheme"
)

// RuntimeClassesClusterGetter has a method to return a RuntimeClassClusterInterface.
// A group's client should implement this interface.
type RuntimeClassesClusterGetter interface {
	RuntimeClasses() RuntimeClassClusterInterface
}

// RuntimeClassInterface has methods to work with RuntimeClass resources.
type RuntimeClassClusterInterface interface {
	Cluster(logicalcluster.Path) nodev1client.RuntimeClassInterface

	List(ctx context.Context, opts v1.ListOptions) (*nodev1.RuntimeClassList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	RuntimeClassExpansion
}

// runtimeClasses implements RuntimeClassInterface
type runtimeClasses struct {
	*gentype.ClientWithListAndApply[*nodev1.RuntimeClass, *nodev1.RuntimeClassList, *applyconfigurationnodev1.RuntimeClassApplyConfiguration]
}

// newRuntimeClasses returns a RuntimeClasses
func newRuntimeClasses(c *NodeV1Client) *runtimeClasses {
	return &runtimeClasses{
		gentype.NewClientWithListAndApply[*nodev1.RuntimeClass, *nodev1.RuntimeClassList, *applyconfigurationnodev1.RuntimeClassApplyConfiguration](
			"runtimeclasses",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *nodev1.RuntimeClass { return &nodev1.RuntimeClass{} },
			func() *nodev1.RuntimeClassList { return &nodev1.RuntimeClassList{} }),
	}
}
