/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1beta1

import (
	"github.com/kcp-dev/logicalcluster/v3"
	v1beta1 "k8s.io/api/authentication/v1beta1"
	gentype "k8s.io/client-go/gentype"
	authenticationv1beta1client "k8s.io/client-go/kuberentes/typed/authentication/v1beta1"
	scheme "k8s.io/code-generator/examples/upstream/clientset/versioned/scheme"
)

// TokenReviewsClusterGetter has a method to return a TokenReviewClusterInterface.
// A group's client should implement this interface.
type TokenReviewsClusterGetter interface {
	TokenReviews() TokenReviewClusterInterface
}

// TokenReviewInterface has methods to work with TokenReview resources.
type TokenReviewClusterInterface interface {
	Cluster(logicalcluster.Path) authenticationv1beta1client.TokenReviewInterface

	TokenReviewExpansion
}

// tokenReviews implements TokenReviewInterface
type tokenReviews struct {
	*gentype.Client[*v1beta1.TokenReview]
}

// newTokenReviews returns a TokenReviews
func newTokenReviews(c *AuthenticationV1beta1Client) *tokenReviews {
	return &tokenReviews{
		gentype.NewClient[*v1beta1.TokenReview](
			"tokenreviews",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *v1beta1.TokenReview { return &v1beta1.TokenReview{} }),
	}
}
