/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"github.com/kcp-dev/logicalcluster/v3"
	v1 "k8s.io/api/authorization/v1"
	gentype "k8s.io/client-go/gentype"
	authorizationv1client "k8s.io/client-go/kuberentes/typed/authorization/v1"
	scheme "k8s.io/code-generator/examples/upstream/clientset/versioned/scheme"
)

// LocalSubjectAccessReviewsClusterGetter has a method to return a LocalSubjectAccessReviewClusterInterface.
// A group's client should implement this interface.
type LocalSubjectAccessReviewsClusterGetter interface {
	LocalSubjectAccessReviews(namespace string) LocalSubjectAccessReviewClusterInterface
}

// LocalSubjectAccessReviewInterface has methods to work with LocalSubjectAccessReview resources.
type LocalSubjectAccessReviewClusterInterface interface {
	Cluster(logicalcluster.Path) authorizationv1client.LocalSubjectAccessReviewInterface

	LocalSubjectAccessReviewExpansion
}

// localSubjectAccessReviews implements LocalSubjectAccessReviewInterface
type localSubjectAccessReviews struct {
	*gentype.Client[*v1.LocalSubjectAccessReview]
}

// newLocalSubjectAccessReviews returns a LocalSubjectAccessReviews
func newLocalSubjectAccessReviews(c *AuthorizationV1Client, namespace string) *localSubjectAccessReviews {
	return &localSubjectAccessReviews{
		gentype.NewClient[*v1.LocalSubjectAccessReview](
			"localsubjectaccessreviews",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *v1.LocalSubjectAccessReview { return &v1.LocalSubjectAccessReview{} }),
	}
}
