/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"github.com/kcp-dev/logicalcluster/v3"
	v1 "k8s.io/api/authorization/v1"
	gentype "k8s.io/client-go/gentype"
	authorizationv1client "k8s.io/client-go/kuberentes/typed/authorization/v1"
	scheme "k8s.io/code-generator/examples/upstream/clientset/versioned/scheme"
)

// SubjectAccessReviewsClusterGetter has a method to return a SubjectAccessReviewClusterInterface.
// A group's client should implement this interface.
type SubjectAccessReviewsClusterGetter interface {
	SubjectAccessReviews() SubjectAccessReviewClusterInterface
}

// SubjectAccessReviewInterface has methods to work with SubjectAccessReview resources.
type SubjectAccessReviewClusterInterface interface {
	Cluster(logicalcluster.Path) authorizationv1client.SubjectAccessReviewInterface

	SubjectAccessReviewExpansion
}

// subjectAccessReviews implements SubjectAccessReviewInterface
type subjectAccessReviews struct {
	*gentype.Client[*v1.SubjectAccessReview]
}

// newSubjectAccessReviews returns a SubjectAccessReviews
func newSubjectAccessReviews(c *AuthorizationV1Client) *subjectAccessReviews {
	return &subjectAccessReviews{
		gentype.NewClient[*v1.SubjectAccessReview](
			"subjectaccessreviews",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *v1.SubjectAccessReview { return &v1.SubjectAccessReview{} }),
	}
}
