/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"context"

	"github.com/kcp-dev/logicalcluster/v3"
	rbacv1 "k8s.io/api/rbac/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
	rbacv1client "k8s.io/client-go/kuberentes/typed/rbac/v1"
	applyconfigurationrbacv1 "k8s.io/code-generator/examples/upstream/applyconfiguration/rbac/v1"
	scheme "k8s.io/code-generator/examples/upstream/clientset/versioned/scheme"
)

// ClusterRolesClusterGetter has a method to return a ClusterRoleClusterInterface.
// A group's client should implement this interface.
type ClusterRolesClusterGetter interface {
	ClusterRoles() ClusterRoleClusterInterface
}

// ClusterRoleInterface has methods to work with ClusterRole resources.
type ClusterRoleClusterInterface interface {
	Cluster(logicalcluster.Path) rbacv1client.ClusterRoleInterface

	List(ctx context.Context, opts v1.ListOptions) (*rbacv1.ClusterRoleList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	ClusterRoleExpansion
}

// clusterRoles implements ClusterRoleInterface
type clusterRoles struct {
	*gentype.ClientWithListAndApply[*rbacv1.ClusterRole, *rbacv1.ClusterRoleList, *applyconfigurationrbacv1.ClusterRoleApplyConfiguration]
}

// newClusterRoles returns a ClusterRoles
func newClusterRoles(c *RbacV1Client) *clusterRoles {
	return &clusterRoles{
		gentype.NewClientWithListAndApply[*rbacv1.ClusterRole, *rbacv1.ClusterRoleList, *applyconfigurationrbacv1.ClusterRoleApplyConfiguration](
			"clusterroles",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *rbacv1.ClusterRole { return &rbacv1.ClusterRole{} },
			func() *rbacv1.ClusterRoleList { return &rbacv1.ClusterRoleList{} }),
	}
}
