/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"context"

	"github.com/kcp-dev/logicalcluster/v3"
	rbacv1 "k8s.io/api/rbac/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
	rbacv1client "k8s.io/client-go/kuberentes/typed/rbac/v1"
	applyconfigurationrbacv1 "k8s.io/code-generator/examples/upstream/applyconfiguration/rbac/v1"
	scheme "k8s.io/code-generator/examples/upstream/clientset/versioned/scheme"
)

// RoleBindingsClusterGetter has a method to return a RoleBindingClusterInterface.
// A group's client should implement this interface.
type RoleBindingsClusterGetter interface {
	RoleBindings(namespace string) RoleBindingClusterInterface
}

// RoleBindingInterface has methods to work with RoleBinding resources.
type RoleBindingClusterInterface interface {
	Cluster(logicalcluster.Path) rbacv1client.RoleBindingInterface

	List(ctx context.Context, opts v1.ListOptions) (*rbacv1.RoleBindingList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	RoleBindingExpansion
}

// roleBindings implements RoleBindingInterface
type roleBindings struct {
	*gentype.ClientWithListAndApply[*rbacv1.RoleBinding, *rbacv1.RoleBindingList, *applyconfigurationrbacv1.RoleBindingApplyConfiguration]
}

// newRoleBindings returns a RoleBindings
func newRoleBindings(c *RbacV1Client, namespace string) *roleBindings {
	return &roleBindings{
		gentype.NewClientWithListAndApply[*rbacv1.RoleBinding, *rbacv1.RoleBindingList, *applyconfigurationrbacv1.RoleBindingApplyConfiguration](
			"rolebindings",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *rbacv1.RoleBinding { return &rbacv1.RoleBinding{} },
			func() *rbacv1.RoleBindingList { return &rbacv1.RoleBindingList{} }),
	}
}
