/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1beta1

import (
	"context"

	"github.com/kcp-dev/logicalcluster/v3"
	v1beta1 "k8s.io/api/flowcontrol/v1beta1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
	flowcontrolv1beta1client "k8s.io/client-go/kuberentes/typed/flowcontrol/v1beta1"
	flowcontrolv1beta1 "k8s.io/code-generator/examples/upstream/applyconfiguration/flowcontrol/v1beta1"
	scheme "k8s.io/code-generator/examples/upstream/clientset/versioned/scheme"
)

// FlowSchemasClusterGetter has a method to return a FlowSchemaClusterInterface.
// A group's client should implement this interface.
type FlowSchemasClusterGetter interface {
	FlowSchemas() FlowSchemaClusterInterface
}

// FlowSchemaInterface has methods to work with FlowSchema resources.
type FlowSchemaClusterInterface interface {
	Cluster(logicalcluster.Path) flowcontrolv1beta1client.FlowSchemaInterface

	List(ctx context.Context, opts v1.ListOptions) (*v1beta1.FlowSchemaList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	FlowSchemaExpansion
}

// flowSchemas implements FlowSchemaInterface
type flowSchemas struct {
	*gentype.ClientWithListAndApply[*v1beta1.FlowSchema, *v1beta1.FlowSchemaList, *flowcontrolv1beta1.FlowSchemaApplyConfiguration]
}

// newFlowSchemas returns a FlowSchemas
func newFlowSchemas(c *FlowcontrolV1beta1Client) *flowSchemas {
	return &flowSchemas{
		gentype.NewClientWithListAndApply[*v1beta1.FlowSchema, *v1beta1.FlowSchemaList, *flowcontrolv1beta1.FlowSchemaApplyConfiguration](
			"flowschemas",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *v1beta1.FlowSchema { return &v1beta1.FlowSchema{} },
			func() *v1beta1.FlowSchemaList { return &v1beta1.FlowSchemaList{} }),
	}
}
