/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"github.com/kcp-dev/logicalcluster/v3"
	v1alpha1 "k8s.io/api/authentication/v1alpha1"
	gentype "k8s.io/client-go/gentype"
	authenticationv1alpha1client "k8s.io/client-go/kuberentes/typed/authentication/v1alpha1"
	scheme "k8s.io/code-generator/examples/upstream/clientset/versioned/scheme"
)

// SelfSubjectReviewsClusterGetter has a method to return a SelfSubjectReviewClusterInterface.
// A group's client should implement this interface.
type SelfSubjectReviewsClusterGetter interface {
	SelfSubjectReviews() SelfSubjectReviewClusterInterface
}

// SelfSubjectReviewInterface has methods to work with SelfSubjectReview resources.
type SelfSubjectReviewClusterInterface interface {
	Cluster(logicalcluster.Path) authenticationv1alpha1client.SelfSubjectReviewInterface

	SelfSubjectReviewExpansion
}

// selfSubjectReviews implements SelfSubjectReviewInterface
type selfSubjectReviews struct {
	*gentype.Client[*v1alpha1.SelfSubjectReview]
}

// newSelfSubjectReviews returns a SelfSubjectReviews
func newSelfSubjectReviews(c *AuthenticationV1alpha1Client) *selfSubjectReviews {
	return &selfSubjectReviews{
		gentype.NewClient[*v1alpha1.SelfSubjectReview](
			"selfsubjectreviews",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *v1alpha1.SelfSubjectReview { return &v1alpha1.SelfSubjectReview{} }),
	}
}
