/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"

	"github.com/kcp-dev/logicalcluster/v3"
	v1alpha1 "k8s.io/api/coordination/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
	coordinationv1alpha1client "k8s.io/client-go/kuberentes/typed/coordination/v1alpha1"
	coordinationv1alpha1 "k8s.io/code-generator/examples/upstream/applyconfiguration/coordination/v1alpha1"
	scheme "k8s.io/code-generator/examples/upstream/clientset/versioned/scheme"
)

// LeaseCandidatesClusterGetter has a method to return a LeaseCandidateClusterInterface.
// A group's client should implement this interface.
type LeaseCandidatesClusterGetter interface {
	LeaseCandidates(namespace string) LeaseCandidateClusterInterface
}

// LeaseCandidateInterface has methods to work with LeaseCandidate resources.
type LeaseCandidateClusterInterface interface {
	Cluster(logicalcluster.Path) coordinationv1alpha1client.LeaseCandidateInterface

	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.LeaseCandidateList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	LeaseCandidateExpansion
}

// leaseCandidates implements LeaseCandidateInterface
type leaseCandidates struct {
	*gentype.ClientWithListAndApply[*v1alpha1.LeaseCandidate, *v1alpha1.LeaseCandidateList, *coordinationv1alpha1.LeaseCandidateApplyConfiguration]
}

// newLeaseCandidates returns a LeaseCandidates
func newLeaseCandidates(c *CoordinationV1alpha1Client, namespace string) *leaseCandidates {
	return &leaseCandidates{
		gentype.NewClientWithListAndApply[*v1alpha1.LeaseCandidate, *v1alpha1.LeaseCandidateList, *coordinationv1alpha1.LeaseCandidateApplyConfiguration](
			"leasecandidates",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *v1alpha1.LeaseCandidate { return &v1alpha1.LeaseCandidate{} },
			func() *v1alpha1.LeaseCandidateList { return &v1alpha1.LeaseCandidateList{} }),
	}
}
