/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"context"

	"github.com/kcp-dev/logicalcluster/v3"
	autoscalingv1 "k8s.io/api/autoscaling/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
	examplegroupv1client "k8s.io/client-go/kuberentes/typed/examplegroup/v1"
	examplev1 "k8s.io/code-generator/examples/HyphenGroup/apis/example/v1"
	applyconfigurationexamplev1 "k8s.io/code-generator/examples/HyphenGroup/applyconfiguration/example/v1"
	scheme "k8s.io/code-generator/examples/HyphenGroup/clientset/versioned/scheme"
)

// ClusterTestTypesClusterGetter has a method to return a ClusterTestTypeClusterInterface.
// A group's client should implement this interface.
type ClusterTestTypesClusterGetter interface {
	ClusterTestTypes() ClusterTestTypeClusterInterface
}

// ClusterTestTypeInterface has methods to work with ClusterTestType resources.
type ClusterTestTypeClusterInterface interface {
	Cluster(logicalcluster.Path) examplegroupv1client.ClusterTestTypeInterface

	List(ctx context.Context, opts v1.ListOptions) (*examplev1.ClusterTestTypeList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)

	UpdateScale(ctx context.Context, clusterTestTypeName string, scale *autoscalingv1.Scale, opts v1.UpdateOptions) (*autoscalingv1.Scale, error)

	ClusterTestTypeExpansion
}

// clusterTestTypes implements ClusterTestTypeInterface
type clusterTestTypes struct {
	*gentype.ClientWithListAndApply[*examplev1.ClusterTestType, *examplev1.ClusterTestTypeList, *applyconfigurationexamplev1.ClusterTestTypeApplyConfiguration]
}

// newClusterTestTypes returns a ClusterTestTypes
func newClusterTestTypes(c *ExampleGroupV1Client) *clusterTestTypes {
	return &clusterTestTypes{
		gentype.NewClientWithListAndApply[*examplev1.ClusterTestType, *examplev1.ClusterTestTypeList, *applyconfigurationexamplev1.ClusterTestTypeApplyConfiguration](
			"clustertesttypes",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *examplev1.ClusterTestType { return &examplev1.ClusterTestType{} },
			func() *examplev1.ClusterTestTypeList { return &examplev1.ClusterTestTypeList{} }),
	}
}

// GetScale takes name of the clusterTestType, and returns the corresponding autoscalingv1.Scale object, and an error if there is any.
func (c *clusterTestTypes) GetScale(ctx context.Context, clusterTestTypeName string, options v1.GetOptions) (result *autoscalingv1.Scale, err error) {
	result = &autoscalingv1.Scale{}
	err = c.GetClient().Get().
		Resource("clustertesttypes").
		Name(clusterTestTypeName).
		SubResource("scale").
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// UpdateScale takes the top resource name and the representation of a scale and updates it. Returns the server's representation of the scale, and an error, if there is any.
func (c *clusterTestTypes) UpdateScale(ctx context.Context, clusterTestTypeName string, scale *autoscalingv1.Scale, opts v1.UpdateOptions) (result *autoscalingv1.Scale, err error) {
	result = &autoscalingv1.Scale{}
	err = c.GetClient().Put().
		Resource("clustertesttypes").
		Name(clusterTestTypeName).
		SubResource("scale").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(scale).
		Do(ctx).
		Into(result)
	return
}
