/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"

	"github.com/kcp-dev/logicalcluster/v3"
	v1alpha1 "k8s.io/api/apiserverinternal/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
	internalv1alpha1client "k8s.io/client-go/kuberentes/typed/internal/v1alpha1"
	apiserverinternalv1alpha1 "k8s.io/code-generator/examples/upstream/applyconfiguration/apiserverinternal/v1alpha1"
	scheme "k8s.io/code-generator/examples/upstream/clientset/versioned/scheme"
)

// StorageVersionsClusterGetter has a method to return a StorageVersionClusterInterface.
// A group's client should implement this interface.
type StorageVersionsClusterGetter interface {
	StorageVersions() StorageVersionClusterInterface
}

// StorageVersionInterface has methods to work with StorageVersion resources.
type StorageVersionClusterInterface interface {
	Cluster(logicalcluster.Path) internalv1alpha1client.StorageVersionInterface

	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.StorageVersionList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	StorageVersionExpansion
}

// storageVersions implements StorageVersionInterface
type storageVersions struct {
	*gentype.ClientWithListAndApply[*v1alpha1.StorageVersion, *v1alpha1.StorageVersionList, *apiserverinternalv1alpha1.StorageVersionApplyConfiguration]
}

// newStorageVersions returns a StorageVersions
func newStorageVersions(c *InternalV1alpha1Client) *storageVersions {
	return &storageVersions{
		gentype.NewClientWithListAndApply[*v1alpha1.StorageVersion, *v1alpha1.StorageVersionList, *apiserverinternalv1alpha1.StorageVersionApplyConfiguration](
			"storageversions",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *v1alpha1.StorageVersion { return &v1alpha1.StorageVersion{} },
			func() *v1alpha1.StorageVersionList { return &v1alpha1.StorageVersionList{} }),
	}
}
