/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1beta1

import (
	"context"

	"github.com/kcp-dev/logicalcluster/v3"
	v1beta1 "k8s.io/api/discovery/v1beta1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
	discoveryv1beta1client "k8s.io/client-go/kuberentes/typed/discovery/v1beta1"
	discoveryv1beta1 "k8s.io/code-generator/examples/upstream/applyconfiguration/discovery/v1beta1"
	scheme "k8s.io/code-generator/examples/upstream/clientset/versioned/scheme"
)

// EndpointSlicesClusterGetter has a method to return a EndpointSliceClusterInterface.
// A group's client should implement this interface.
type EndpointSlicesClusterGetter interface {
	EndpointSlices(namespace string) EndpointSliceClusterInterface
}

// EndpointSliceInterface has methods to work with EndpointSlice resources.
type EndpointSliceClusterInterface interface {
	Cluster(logicalcluster.Path) discoveryv1beta1client.EndpointSliceInterface

	List(ctx context.Context, opts v1.ListOptions) (*v1beta1.EndpointSliceList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	EndpointSliceExpansion
}

// endpointSlices implements EndpointSliceInterface
type endpointSlices struct {
	*gentype.ClientWithListAndApply[*v1beta1.EndpointSlice, *v1beta1.EndpointSliceList, *discoveryv1beta1.EndpointSliceApplyConfiguration]
}

// newEndpointSlices returns a EndpointSlices
func newEndpointSlices(c *DiscoveryV1beta1Client, namespace string) *endpointSlices {
	return &endpointSlices{
		gentype.NewClientWithListAndApply[*v1beta1.EndpointSlice, *v1beta1.EndpointSliceList, *discoveryv1beta1.EndpointSliceApplyConfiguration](
			"endpointslices",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *v1beta1.EndpointSlice { return &v1beta1.EndpointSlice{} },
			func() *v1beta1.EndpointSliceList { return &v1beta1.EndpointSliceList{} }),
	}
}
