/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"context"

	"github.com/kcp-dev/logicalcluster/v3"
	appsv1 "k8s.io/api/apps/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
	appsv1client "k8s.io/client-go/kuberentes/typed/apps/v1"
	applyconfigurationappsv1 "k8s.io/code-generator/examples/upstream/applyconfiguration/apps/v1"
	scheme "k8s.io/code-generator/examples/upstream/clientset/versioned/scheme"
)

// DaemonSetsClusterGetter has a method to return a DaemonSetClusterInterface.
// A group's client should implement this interface.
type DaemonSetsClusterGetter interface {
	DaemonSets(namespace string) DaemonSetClusterInterface
}

// DaemonSetInterface has methods to work with DaemonSet resources.
type DaemonSetClusterInterface interface {
	Cluster(logicalcluster.Path) appsv1client.DaemonSetInterface

	List(ctx context.Context, opts v1.ListOptions) (*appsv1.DaemonSetList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	DaemonSetExpansion
}

// daemonSets implements DaemonSetInterface
type daemonSets struct {
	*gentype.ClientWithListAndApply[*appsv1.DaemonSet, *appsv1.DaemonSetList, *applyconfigurationappsv1.DaemonSetApplyConfiguration]
}

// newDaemonSets returns a DaemonSets
func newDaemonSets(c *AppsV1Client, namespace string) *daemonSets {
	return &daemonSets{
		gentype.NewClientWithListAndApply[*appsv1.DaemonSet, *appsv1.DaemonSetList, *applyconfigurationappsv1.DaemonSetApplyConfiguration](
			"daemonsets",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *appsv1.DaemonSet { return &appsv1.DaemonSet{} },
			func() *appsv1.DaemonSetList { return &appsv1.DaemonSetList{} }),
	}
}
