/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1beta2

import (
	"context"

	"github.com/kcp-dev/logicalcluster/v3"
	v1beta2 "k8s.io/api/apps/v1beta2"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
	appsv1beta2client "k8s.io/client-go/kuberentes/typed/apps/v1beta2"
	appsv1beta2 "k8s.io/code-generator/examples/upstream/applyconfiguration/apps/v1beta2"
	scheme "k8s.io/code-generator/examples/upstream/clientset/versioned/scheme"
)

// ReplicaSetsClusterGetter has a method to return a ReplicaSetClusterInterface.
// A group's client should implement this interface.
type ReplicaSetsClusterGetter interface {
	ReplicaSets(namespace string) ReplicaSetClusterInterface
}

// ReplicaSetInterface has methods to work with ReplicaSet resources.
type ReplicaSetClusterInterface interface {
	Cluster(logicalcluster.Path) appsv1beta2client.ReplicaSetInterface

	List(ctx context.Context, opts v1.ListOptions) (*v1beta2.ReplicaSetList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	ReplicaSetExpansion
}

// replicaSets implements ReplicaSetInterface
type replicaSets struct {
	*gentype.ClientWithListAndApply[*v1beta2.ReplicaSet, *v1beta2.ReplicaSetList, *appsv1beta2.ReplicaSetApplyConfiguration]
}

// newReplicaSets returns a ReplicaSets
func newReplicaSets(c *AppsV1beta2Client, namespace string) *replicaSets {
	return &replicaSets{
		gentype.NewClientWithListAndApply[*v1beta2.ReplicaSet, *v1beta2.ReplicaSetList, *appsv1beta2.ReplicaSetApplyConfiguration](
			"replicasets",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *v1beta2.ReplicaSet { return &v1beta2.ReplicaSet{} },
			func() *v1beta2.ReplicaSetList { return &v1beta2.ReplicaSetList{} }),
	}
}
