/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1beta1

import (
	"context"

	"github.com/kcp-dev/logicalcluster/v3"
	v1beta1 "k8s.io/api/storage/v1beta1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
	storagev1beta1client "k8s.io/client-go/kuberentes/typed/storage/v1beta1"
	storagev1beta1 "k8s.io/code-generator/examples/upstream/applyconfiguration/storage/v1beta1"
	scheme "k8s.io/code-generator/examples/upstream/clientset/versioned/scheme"
)

// CSINodesClusterGetter has a method to return a CSINodeClusterInterface.
// A group's client should implement this interface.
type CSINodesClusterGetter interface {
	CSINodes() CSINodeClusterInterface
}

// CSINodeInterface has methods to work with CSINode resources.
type CSINodeClusterInterface interface {
	Cluster(logicalcluster.Path) storagev1beta1client.CSINodeInterface

	List(ctx context.Context, opts v1.ListOptions) (*v1beta1.CSINodeList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	CSINodeExpansion
}

// cSINodes implements CSINodeInterface
type cSINodes struct {
	*gentype.ClientWithListAndApply[*v1beta1.CSINode, *v1beta1.CSINodeList, *storagev1beta1.CSINodeApplyConfiguration]
}

// newCSINodes returns a CSINodes
func newCSINodes(c *StorageV1beta1Client) *cSINodes {
	return &cSINodes{
		gentype.NewClientWithListAndApply[*v1beta1.CSINode, *v1beta1.CSINodeList, *storagev1beta1.CSINodeApplyConfiguration](
			"csinodes",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *v1beta1.CSINode { return &v1beta1.CSINode{} },
			func() *v1beta1.CSINodeList { return &v1beta1.CSINodeList{} }),
	}
}
