/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"context"

	"github.com/kcp-dev/logicalcluster/v3"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
	thirdexamplev1client "k8s.io/client-go/kuberentes/typed/thirdexample/v1"
	example3iov1 "k8s.io/code-generator/examples/apiserver/apis/example3.io/v1"
	scheme "k8s.io/code-generator/examples/apiserver/clientset/versioned/scheme"
)

// TestTypesClusterGetter has a method to return a TestTypeClusterInterface.
// A group's client should implement this interface.
type TestTypesClusterGetter interface {
	TestTypes(namespace string) TestTypeClusterInterface
}

// TestTypeInterface has methods to work with TestType resources.
type TestTypeClusterInterface interface {
	Cluster(logicalcluster.Path) thirdexamplev1client.TestTypeInterface

	List(ctx context.Context, opts v1.ListOptions) (*example3iov1.TestTypeList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	TestTypeExpansion
}

// testTypes implements TestTypeInterface
type testTypes struct {
	*gentype.ClientWithList[*example3iov1.TestType, *example3iov1.TestTypeList]
}

// newTestTypes returns a TestTypes
func newTestTypes(c *ThirdExampleV1Client, namespace string) *testTypes {
	return &testTypes{
		gentype.NewClientWithList[*example3iov1.TestType, *example3iov1.TestTypeList](
			"testtypes",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *example3iov1.TestType { return &example3iov1.TestType{} },
			func() *example3iov1.TestTypeList { return &example3iov1.TestTypeList{} }),
	}
}
