/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1beta1

import (
	"context"

	"github.com/kcp-dev/logicalcluster/v3"
	v1beta1 "k8s.io/api/apps/v1beta1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
	appsv1beta1client "k8s.io/client-go/kuberentes/typed/apps/v1beta1"
	appsv1beta1 "k8s.io/code-generator/examples/upstream/applyconfiguration/apps/v1beta1"
	scheme "k8s.io/code-generator/examples/upstream/clientset/versioned/scheme"
)

// ControllerRevisionsClusterGetter has a method to return a ControllerRevisionClusterInterface.
// A group's client should implement this interface.
type ControllerRevisionsClusterGetter interface {
	ControllerRevisions(namespace string) ControllerRevisionClusterInterface
}

// ControllerRevisionInterface has methods to work with ControllerRevision resources.
type ControllerRevisionClusterInterface interface {
	Cluster(logicalcluster.Path) appsv1beta1client.ControllerRevisionInterface

	List(ctx context.Context, opts v1.ListOptions) (*v1beta1.ControllerRevisionList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	ControllerRevisionExpansion
}

// controllerRevisions implements ControllerRevisionInterface
type controllerRevisions struct {
	*gentype.ClientWithListAndApply[*v1beta1.ControllerRevision, *v1beta1.ControllerRevisionList, *appsv1beta1.ControllerRevisionApplyConfiguration]
}

// newControllerRevisions returns a ControllerRevisions
func newControllerRevisions(c *AppsV1beta1Client, namespace string) *controllerRevisions {
	return &controllerRevisions{
		gentype.NewClientWithListAndApply[*v1beta1.ControllerRevision, *v1beta1.ControllerRevisionList, *appsv1beta1.ControllerRevisionApplyConfiguration](
			"controllerrevisions",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *v1beta1.ControllerRevision { return &v1beta1.ControllerRevision{} },
			func() *v1beta1.ControllerRevisionList { return &v1beta1.ControllerRevisionList{} }),
	}
}
